library(tteICE)
example("scr.tteICE")
example("surv.tteICE")
example("tteICE")
example("tteICEShiny", ask = FALSE)
example("bshaz.tteICE")
example("coef.tteICE")
example("plot.tteICE", ask = FALSE)
example("predict.tteICE")
example("print.tteICE")
example("summary.tteICE")
example("zph.tteICE", ask = FALSE)